src/main/java/org/application/domain/ItemType.java
package org.application.domain;

public enum ItemType {

    FOOD, BEVERAGES, MACHINE;
}

src/main/java/org/application/web/ItemBean.java
package org.application.web;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;
import javax.persistence.PersistenceException;

import org.application.domain.ItemEntity;
import org.application.domain.ItemType;
import org.application.domain.ProductEntity;
import org.application.service.ItemService;
import org.application.service.ProductService;
import org.application.service.security.SecurityWrapper;
import org.application.web.util.MessageFactory;
import org.primefaces.event.TransferEvent;
import org.primefaces.model.DualListModel;

@Named("itemBean")
@ViewScoped
public class ItemBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private static final Logger logger = Logger.getLogger(ItemBean.class.getName());
    
    private List<ItemEntity> itemList;

    private ItemEntity item;
    
    @Inject
    private ItemService itemService;
    
    @Inject
    private ProductService productService;
    
    private DualListModel<ProductEntity> products;
    private List<String> transferedProductIDs;
    private List<String> removedProductIDs;
    
    public void prepareNewItem() {
        reset();
        this.item = new ItemEntity();
        // set any default values now, if you need
        // Example: this.item.setAnything("test");
    }

    public String persist() {

        if (item.getId() == null && !isPermitted("item:create")) {
            return "accessDenied";
        } else if (item.getId() != null && !isPermitted(item, "item:update")) {
            return "accessDenied";
        }
        
        String message = "";
        
        try {
            
            if (item.getId() != null) {
                item = itemService.update(item);
                message = "message_successfully_updated";
            } else {
                item = itemService.save(item);
                message = "message_successfully_created";
            }
        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_optimistic_locking_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_save_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        
        itemList = null;

        FacesMessage facesMessage = MessageFactory.getMessage(message);
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
        
        FacesContext.getCurrentInstance().getExternalContext().getFlash().setKeepMessages(true);
        
        return null;
    }
    
    public String delete() {
        
        if (!isPermitted(item, "item:delete")) {
            return "accessDenied";
        }
        
        String message = "";
        
        try {
            itemService.delete(item);
            message = "message_successfully_deleted";
            reset();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_delete_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        FacesContext.getCurrentInstance().addMessage(null, MessageFactory.getMessage(message));
        
        return null;
    }
    
    public void reset() {
        item = null;
        itemList = null;
        
        products = null;
        transferedProductIDs = null;
        removedProductIDs = null;
        
    }

    public DualListModel<ProductEntity> getProducts() {
        return products;
    }

    public void setProducts(DualListModel<ProductEntity> products) {
        this.products = products;
    }
    
    public List<ProductEntity> getFullProductsList() {
        List<ProductEntity> allList = new ArrayList<ProductEntity>();
        allList.addAll(products.getSource());
        allList.addAll(products.getTarget());
        return allList;
    }
    
    public void onProductsDialog(ItemEntity item) {
        // Prepare the product PickList
        this.item = item;
        List<ProductEntity> selectedProductsFromDB = productService
                .findProductsByItems(this.item);
        List<ProductEntity> availableProductsFromDB = productService
                .findAvailableProducts(this.item);
        this.products = new DualListModel<>(availableProductsFromDB, selectedProductsFromDB);
        
        transferedProductIDs = new ArrayList<String>();
        removedProductIDs = new ArrayList<String>();
    }
    
    public void onProductsPickListTransfer(TransferEvent event) {
        // If a product is transferred within the PickList, we just transfer it in this
        // bean scope. We do not change anything it the database, yet.
        for (Object item : event.getItems()) {
            String id = ((ProductEntity) item).getId().toString();
            if (event.isAdd()) {
                transferedProductIDs.add(id);
                removedProductIDs.remove(id);
            } else if (event.isRemove()) {
                removedProductIDs.add(id);
                transferedProductIDs.remove(id);
            }
        }
        
    }
    
    public void updateProduct(ProductEntity product) {
        // If a new product is created, we persist it to the database,
        // but we do not assign it to this item in the database, yet.
        products.getTarget().add(product);
        transferedProductIDs.add(product.getId().toString());
    }
    
    public void onProductsSubmit() {
        // Now we save the changed of the PickList to the database.
        try {
            List<ProductEntity> selectedProductsFromDB = productService
                    .findProductsByItems(this.item);
            List<ProductEntity> availableProductsFromDB = productService
                    .findAvailableProducts(this.item);
            
            for (ProductEntity product : selectedProductsFromDB) {
                if (removedProductIDs.contains(product.getId().toString())) {
                    product.setItems(null);
                    productService.update(product);
                }
            }
    
            for (ProductEntity product : availableProductsFromDB) {
                if (transferedProductIDs.contains(product.getId().toString())) {
                    product.setItems(item);
                    productService.update(product);
                }
            }
            
            FacesMessage facesMessage = MessageFactory.getMessage(
                    "message_changes_saved");
            FacesContext.getCurrentInstance().addMessage(null, facesMessage);
            FacesContext.getCurrentInstance().getExternalContext().getFlash().setKeepMessages(true);
            
            reset();

        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            FacesMessage facesMessage = MessageFactory.getMessage(
                    "message_optimistic_locking_exception");
            FacesContext.getCurrentInstance().addMessage(null, facesMessage);
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            FacesMessage facesMessage = MessageFactory.getMessage(
                    "message_picklist_save_exception");
            FacesContext.getCurrentInstance().addMessage(null, facesMessage);
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
    }
    
    public SelectItem[] getTypeSelectItems() {
        SelectItem[] items = new SelectItem[ItemType.values().length];

        int i = 0;
        for (ItemType type : ItemType.values()) {
            items[i++] = new SelectItem(type, getLabelForType(type));
        }
        return items;
    }
    
    public String getLabelForType(ItemType value) {
        if (value == null) {
            return "";
        }
        String label = MessageFactory.getMessageString(
                "enum_label_item_type_" + value);
        return label == null? value.toString() : label;
    }
    
    public ItemEntity getItem() {
        if (this.item == null) {
            prepareNewItem();
        }
        return this.item;
    }
    
    public void setItem(ItemEntity item) {
        this.item = item;
    }
    
    public List<ItemEntity> getItemList() {
        if (itemList == null) {
            itemList = itemService.findAllItemEntities();
        }
        return itemList;
    }

    public void setItemList(List<ItemEntity> itemList) {
        this.itemList = itemList;
    }
    
    public boolean isPermitted(String permission) {
        return SecurityWrapper.isPermitted(permission);
    }

    public boolean isPermitted(ItemEntity item, String permission) {
        
        return SecurityWrapper.isPermitted(permission);
        
    }
    
}

src/main/webapp/pages/item/item.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui"
      xmlns:dialog="http://java.sun.com/jsf/composite/dialog">
<ui:composition template="/templates/layout.xhtml">
  <ui:define name="content">

    <h:form prependId="false" id="itemDataForm" onkeypress="if (event.keyCode == 13) {return false; }">

        <p:dataTable id="itemTable" value="#{itemBean.itemList}" var="item" resizableColumns="true" paginator="true"
                paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                rowsPerPageTemplate="5,10,25,50" rows="10" draggableColumns="true"
                paginatorPosition="bottom" widgetVar="itemTable" emptyMessage="#{messages.label_no_records_found}"
                reflow="true">
        
          <f:facet name="header" >

              <p:commandButton value="#{messages.create_new_item}" icon="ui-icon-plusthick"
                      action="/pages/item/itemCreate?faces-redirect=true"
                      rendered="#{itemBean.isPermitted('item:create')}" style="float:left" />
              
              <p:commandButton id="toggler" type="button" value="#{messages.table_select_columns}" icon="ui-icon-calculator" />
              <p:columnToggler datasource="itemTable" trigger="toggler" />
          </f:facet>
          
          <p:column headerText="#{messages.field_label_item_date}" sortBy="#{item.date}" filterBy="#{item.date}">
            <f:facet name="filter">
                <p:inputText id="dateFilter"
                        onkeyup="if (event.keyCode == 13) {PF('itemTable').filter(); updateDateFilter(); return false;}" >
                    <p:remoteCommand name="updateDateFilter" update="itemTable:dateFilter" />
                    <f:convertDateTime />
                </p:inputText>
            </f:facet>
            <h:outputText value="#{item.date}"><f:convertDateTime /></h:outputText>
          </p:column>

          <p:column headerText="#{messages.field_label_item_product_plural}" styleClass="action-column" exportable="false">
            
            <p:commandButton icon="ui-icon-transfer-e-w"  title="#{messages.field_label_item_product_plural}" action="#{'/pages/item/itemProduct?faces-redirect=true&amp;id='.concat(item.id)}" />
            
          </p:column>
          
          <p:column styleClass="action-column" headerText="#{messages.table_actions_column}" width="115" exportable="false">
            
            <p:commandButton action="#{'/pages/item/itemView?faces-redirect=true&amp;id='.concat(item.id)}"
                icon="ui-icon-zoomin"
                title="#{messages.label_view}" />
            
            <p:commandButton action="#{'/pages/item/itemEdit?faces-redirect=true&amp;id='.concat(item.id)}"
                icon="ui-icon-pencil"
                resetValues="true"
                rendered="#{itemBean.isPermitted(item, 'item:update')}"
                title="#{messages.label_edit}" />
                
            <p:commandButton icon="ui-icon-close" rendered="#{itemBean.isPermitted(item, 'item:delete')}"
                oncomplete="PF('deleteItemDialogWidget').show()"
                title="#{messages.label_delete}" >
                <f:setPropertyActionListener value="#{item}"
                    target="#{itemBean.item}" />
            </p:commandButton>
    
          </p:column>
          
        </p:dataTable>
        
    </h:form>

    <p:confirmDialog id="deleteItemDialog" widgetVar="deleteItemDialogWidget"
        rendered="#{itemBean.isPermitted(itemBean.item, 'item:delete')}" header="#{messages.label_confirm_deletion}"
        severity="alarm">
        <f:facet name="message"><h:outputText value="#{messages.label_delete_record}" escape="false"/></f:facet>
        <p:outputPanel>
          <h:form>
            <div style="text-align: center; margin:10px">
              <p:commandButton value="#{messages.label_yes}" action="#{itemBean.delete}" update=":itemDataForm :growlForm:growl" oncomplete="PF('deleteItemDialogWidget').hide()" />
              <p:commandButton value="#{messages.label_no}" onclick="PF('deleteItemDialogWidget').hide()" type="button" />
            </div>
          </h:form>
        </p:outputPanel>
    </p:confirmDialog>
    
  </ui:define>
</ui:composition>
</html>

src/main/webapp/pages/item/itemCreate.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <ui:include src="/pages/item/itemEdit.xhtml" />

</html>

src/main/webapp/pages/item/itemEdit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
<ui:composition template="/templates/layout.xhtml">
  <ui:define name="content">
  
    <f:metadata>
      <f:viewParam name="id" value="#{itemBean.item}" converter="#{genericEntityConverter}" />
    </f:metadata>
    
    <p:outputPanel id="itemEditPanel">
        <h:form id="editItemForm">
            <ui:include src="/pages/item/itemEditInclude.xhtml"/>
            <div style="margin:10px">
                <p:commandButton value="#{messages.label_save}" icon="ui-icon-disk" actionListener="#{itemBean.persist}"
                        action="/pages/item/item?faces-redirect=true" update=":itemEditPanel :growlForm:growl" />
                <p:commandButton value="#{messages.label_close}" icon="ui-icon-close"
                        action="/pages/item/item?faces-redirect=true" immediate="true" />
            </div>
        </h:form>
    </p:outputPanel>
    
  </ui:define>
  
</ui:composition>
</html>

src/main/webapp/pages/item/itemEditInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

        <p:outputPanel styleClass="ui-fluid">

            <p:panelGrid columns="3" columnClasses="ui-grid-col-4,ui-grid-col-6,ui-grid-col-2" layout="grid" style="max-width:400px">
            
                <h:outputText value="#{messages.field_label_item_date}:" for="dateEditInput" />
                <p:calendar id="dateEditInput" navigator="true" value="#{itemBean.item.date}" label="#{messages.field_label_item_date}" />
                <p:message for="dateEditInput" display="icon" />

                <h:outputText value="#{messages.field_label_item_type}:" for="typeSelect"/>
                <p:selectManyCheckbox value="#{itemBean.item.type}" converter="omnifaces.GenericEnumConverter"
                        id="typeSelect" layout="responsive" columns="1">
                    <f:selectItems value="#{itemBean.typeSelectItems}" />
                    <f:attribute name="collectionType" value="java.util.HashSet" />
                </p:selectManyCheckbox>
                <p:message for="typeSelect" display="icon" />

            </p:panelGrid>

        </p:outputPanel>
</html>

src/main/webapp/pages/item/itemProduct.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
<ui:composition template="/templates/layout.xhtml">
  <ui:define name="content">
  
    <f:metadata>
      <f:viewParam name="id" value="#{itemBean.item}" converter="#{genericEntityConverter}" />
      <f:viewAction action="#{itemBean.onProductsDialog(itemBean.item)}"/>
    </f:metadata>
    
    <p:outputPanel styleClass="ui-fluid" rendered="#{not itemBean.isPermitted(itemBean.item, 'item:read')}">
        <h:outputText value="#{messages.access_denied}" />
    </p:outputPanel>
    
    <p:outputPanel id="itemProductsPanel" rendered="#{itemBean.isPermitted(itemBean.item, 'item:read')}">
        <h:form id="itemProductsForm">
            <ui:include src="/pages/item/itemProductInclude.xhtml" />
            <div style="margin:10px">
                <p:commandButton value="#{messages.label_save}"
                    icon="ui-icon-disk"
                    actionListener="#{itemBean.onProductsSubmit}"
                    action="/pages/item/item?faces-redirect=true"
                    update=":growlForm:growl"
                    rendered="#{itemBean.isPermitted(itemBean.item, 'item:update')}"
                    partialSubmit="true" process="@this" />
                <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" action="/pages/item/item?faces-redirect=true" />
            </div>
        </h:form>
    </p:outputPanel>
    
    <p:dialog dynamic="true" id="createProductDialog"
        header="#{messages.dialog_item_create_product}" modal="true"
        widgetVar="createProductDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{productBean.reset}" />
        <p:outputPanel id="createProductPanel">
                <h:form id="createProductForm">
                    <ui:include src="/pages/product/productEditInclude.xhtml">
                        <ui:param name="hideItemsSelectInput" value="true" />
                    </ui:include>
                    <div style="text-align: center; margin: 10px">
                        <p:commandButton
                            action="#{itemBean.updateProduct(productBean.product)}"
                            value="#{messages.label_save}" icon="ui-icon-disk"
                            actionListener="#{productBean.persist}"
                            update=":itemProductsPanel :createProductPanel :growlForm:growl"
                            oncomplete="if(!args.validationFailed) PF('createProductDialogWidget').hide()" />
                        <p:commandButton value="#{messages.label_close}"
                            icon="ui-icon-close"
                            onclick="PF('createProductDialogWidget').hide()"
                            type="button" />
                    </div>
                </h:form>
            </p:outputPanel>
    </p:dialog>
    
  </ui:define>
  
</ui:composition>
</html>

src/main/webapp/pages/item/itemProductInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
      
    <p:outputPanel styleClass="ui-fluid" rendered="#{not itemBean.isPermitted(itemBean.item, 'item:read')}">
        <h:outputText value="#{messages.access_denied}" />
    </p:outputPanel>
    
    <h:panelGrid rendered="#{itemBean.isPermitted(itemBean.item, 'item:read')}">
       
       <p:commandButton value="#{messages.dialog_item_create_product}" icon="ui-icon-plusthick" title="#{messages.label_create}"
                  actionListener="#{productBean.prepareNewProduct()}"
                  update=":createProductDialog :growlForm:growl" resetValues="true"
                  oncomplete="PF('createProductDialogWidget').show()" partialSubmit="true" process="@this"
                  rendered="#{itemBean.isPermitted('product:create') and itemBean.isPermitted(itemBean.item, 'item:update')}"
                  style="float:right;">
       </p:commandButton>
       
       <p:pickList id="itemProductsPickList" var="product" itemLabel="#{product.name}"
                   value="#{itemBean.products}" itemValue="#{product}"
                   showSourceFilter="true" showTargetFilter="true" filterMatchMode="contains"
                   disabled="#{not itemBean.isPermitted(itemBean.item, 'item:update')}">
         <o:converter converterId="omnifaces.ListConverter" list="#{itemBean.fullProductsList}" />
         <p:ajax event="transfer" listener="#{itemBean.onProductsPickListTransfer}" partialSubmit="true" process="@this" />
         <f:facet name="sourceCaption"><h:outputText value="#{messages.label_picklist_available}" /></f:facet>
         <f:facet name="targetCaption"><h:outputText value="#{messages.label_picklist_assigned}" /></f:facet>
       </p:pickList>
</h:panelGrid>
</html>

src/main/webapp/pages/item/itemView.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
<ui:composition template="/templates/layout.xhtml">
  <ui:define name="content">
  
    <f:metadata>
      <f:viewParam name="id" value="#{itemBean.item}" converter="#{genericEntityConverter}" />
    </f:metadata>
    
    <p:outputPanel styleClass="ui-fluid" rendered="#{not itemBean.isPermitted(itemBean.item, 'item:read')}">
        <h:outputText value="#{messages.access_denied}" />
    </p:outputPanel>
    
    <p:outputPanel id="itemViewPanel" rendered="#{itemBean.isPermitted(itemBean.item, 'item:read')}">
        <h:form id="viewItemForm">
            <ui:include src="/pages/item/itemViewInclude.xhtml"/>
            <div style="margin:10px">
                <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" action="/pages/item/item?faces-redirect=true" immediate="true"/>
            </div>
        </h:form>
    </p:outputPanel>
  
  </ui:define>
  
</ui:composition>
</html>

src/main/webapp/pages/item/itemViewInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <p:outputPanel styleClass="ui-fluid" rendered="#{not itemBean.isPermitted(itemBean.item, 'item:read')}">
        <h:outputText value="#{messages.access_denied}" />
    </p:outputPanel>
    
    <h:panelGrid columns="2" styleClass="dialog" columnClasses="col1,col2" rendered="#{itemBean.isPermitted(itemBean.item, 'item:read')}">
        
        <h:outputText value="#{messages.field_label_item_date}:" />
        <h:outputText value="#{itemBean.item.date}" ><f:convertDateTime /></h:outputText>

        <h:outputText value="#{messages.field_label_item_type}:" />
        <p:outputPanel>
            <ui:repeat value="#{itemBean.item.type.toArray()}" var="type">
                <h:outputText value="#{itemBean.getLabelForType(type)}" /><br/>
            </ui:repeat>
        </p:outputPanel>

    </h:panelGrid>
</html>