src/main/java/org/application/web/util/LocaleBean.java
package org.application.web.util;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.inject.Named;

@Named
@SessionScoped
public class LocaleBean implements Serializable {
	
	private static final long serialVersionUID = 1L;
    private Locale locale;

    @PostConstruct
    public void init() {
        this.locale = FacesContext.getCurrentInstance().getExternalContext().getRequestLocale();
    }

    public Locale getLocale() {
        return this.locale;
    }

    /**
     * Returns an array of all supported locales to display them in the language selector
     * @return Array of SelectItem
     */
    public SelectItem[] getLocales() {
        List<SelectItem> items = new ArrayList<SelectItem>();
        Iterator<Locale> supportedLocales = FacesContext.getCurrentInstance().getApplication().getSupportedLocales();
        while (supportedLocales.hasNext()) {
            Locale locale = supportedLocales.next();
            items.add(new SelectItem(locale.toString(), locale.getDisplayName(locale)));
        }
        return items.toArray(new SelectItem[] {});
    }

    public String getSelectedLocale() {
    	if (this.locale == null || this.locale.getLanguage() == null) {
    		return null;
    	}
        return this.locale.getLanguage().toString();
    }
    
   public void setSelectedLocale(String localeString) {
        Iterator<Locale> supportedLocales = FacesContext.getCurrentInstance().getApplication().getSupportedLocales();
        while (supportedLocales.hasNext()) {
            Locale locale = supportedLocales.next();
            if (locale.toString().equals(localeString)) {
            	this.locale = locale;
                break;
            }
        }
    }
}

src/main/webapp/templates/header.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<ui:composition>
  <title>#{messages.application_name}</title>
  <h:outputScript library="js" name="calendar.js" />
</ui:composition>
</html>

src/main/webapp/templates/layout.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://java.sun.com/jsp/jstl/core">

<f:view locale="#{localeBean.locale}" contentType="text/html">
<ui:debug hotkey="x" rendered="#{facesContext.application.projectStage eq 'Development'}"></ui:debug>
<h:head>
  <ui:insert name="header">
    <ui:include src="header.xhtml" />
  </ui:insert>
</h:head>
<h:body>
    <h:outputStylesheet library="css" name="standard.css" />
    <h:form prependId="false" id="growlForm">
      <p:growl id="growl" showDetail="false" />
    </h:form>

    <div style="padding: 4px 10px">
        <ui:include src="toolbar.xhtml" />
    </div>

    <div class="ui-fluid">
        <p:panelGrid columns="2" columnClasses="ui-grid-col-2,ui-grid-col-10" layout="grid">
            <ui:insert name="menu">
              <ui:include src="menu.xhtml" />
            </ui:insert>

            <h:panelGroup>
                <ui:insert name="content" />
            </h:panelGroup>
        </p:panelGrid>
    </div>
</h:body>
</f:view>
</html>

src/main/webapp/templates/menu.xhtml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<ui:composition>
  <h:form>
  <p:menu>
    <p:submenu label="#{messages.menu_pages}">
      
      <p:menuitem value="#{messages.menu_products}" url="/pages/product/product.xhtml" icon="icon-entity" ajax="false" async="false" />
      
      <p:menuitem value="#{messages.menu_items}" url="/pages/item/item.xhtml" icon="icon-entity" ajax="false" async="false" />
      
      <p:menuitem value="#{messages.menu_attachements}" url="/pages/attachement/attachement.xhtml" icon="icon-entity" ajax="false" async="false" />
      
    </p:submenu>
    
    <p:submenu label="#{messages.menu_admin}" rendered="#{p:ifGranted('Administrator')}">
      <p:menuitem value="#{messages.menu_user_management}" url="/pages/admin/user.xhtml" icon="ui-icon-person" ajax="false" async="false"/>
    </p:submenu>
    
  </p:menu>
  </h:form>
</ui:composition>
</html>

src/main/webapp/templates/toolbar.xhtml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<ui:composition>
  <h:form>
    <h:link outcome="/pages/main" style="float:left">
      <h:graphicImage name="images/logo.png" alt="logo" height="48px" style="margin-right:10px"/>
    </h:link>
    <span style="font-size:2em;color:#777777;height:48px;vertical-align:middle;display:table-cell;">
      <h:outputText value="#{messages.application_name}" />
    </span>
    <p:toolbar style="margin-top:5px">
      <f:facet name="left">
        <p:button outcome="/pages/main" value="#{messages.toolbar_home}" icon="ui-icon-home" />
      </f:facet>
      <f:facet name="right">
        <p:selectOneMenu value="#{localeBean.selectedLocale}" style="vertical-align:bottom;margin-right:10px">
          <p:ajax update="@all" />
          <f:selectItems value="#{localeBean.locales}" ></f:selectItems>
        </p:selectOneMenu>
        
        <p:button outcome="/login" value="#{messages.toolbar_login}" icon="ui-icon-key"
                  rendered="#{empty request.remoteUser}"/>
        <h:outputText value=" #{messages.toolbar_user}: #{request.remoteUser}" rendered="#{not empty request.remoteUser}"
                  style="margin-right:10px"/>
        <p:button outcome="/pages/user/profile" value="#{messages.toolbar_profile}" icon="ui-icon-person"
                           rendered="#{not empty request.remoteUser}" ajax="false"/>
        <p:commandButton action="#{loginBean.logout}" value="#{messages.toolbar_logout}" icon="ui-icon-key"
                      rendered="#{not empty request.remoteUser}" ajax="false"/>
        
      </f:facet>
    </p:toolbar>
  </h:form>
</ui:composition>
</html>