src/main/java/org/application/web/security/UserBean.java
package org.application.web.security;

import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;
import javax.persistence.PersistenceException;

import org.application.domain.security.UserEntity;
import org.application.domain.security.UserRole;
import org.application.domain.security.UserStatus;
import org.application.service.security.SecurityWrapper;
import org.application.service.security.UserService;
import org.application.web.generic.GenericLazyDataModel;
import org.application.web.util.MessageFactory;
import org.primefaces.model.LazyDataModel;

@Named
@ViewScoped
public class UserBean implements Serializable {
    
    private static final Logger logger = Logger.getLogger(UserBean.class.getName());
    
    private LazyDataModel<UserEntity> lazyModel;

    private static final long serialVersionUID = 1L;

    private UserEntity user;

    @Inject
    private UserService userService;
    
    public UserEntity getUser() {
        if (user == null) {
            user = new UserEntity();
        }
        return user;
    }

    public void setUser(UserEntity user) {
        this.user = user;
    }

    public void prepareNewUser() {
        this.user = new UserEntity();
        // set any default values now, if you need
    }
    
    public LazyDataModel<UserEntity> getLazyModel() {
        if (this.lazyModel == null) {
            this.lazyModel = new GenericLazyDataModel<UserEntity>(userService);
        }
        return this.lazyModel;
    }
    
    public void persist() {

        String message = "";
        
        try {
            
            if (user.getId() != null) {
                user = userService.update(user);
                message = "message_successfully_updated";
            } else {
                
                // Check if a user with same username already exists
                if (userService.findUserByUsername(user.getUsername()) != null) {
                    FacesMessage facesMessage = MessageFactory.getMessage(
                            "user_username_exists");
                    facesMessage.setSeverity(FacesMessage.SEVERITY_ERROR);
                    FacesContext.getCurrentInstance().addMessage(null, facesMessage);
                    FacesContext.getCurrentInstance().validationFailed();
                    return;
                }
                // Check if a user with same email already exists            
                if (userService.findUserByEmail(user.getEmail()) != null) {
                    FacesMessage facesMessage = MessageFactory.getMessage(
                            "user_email_exists");
                    facesMessage.setSeverity(FacesMessage.SEVERITY_ERROR);
                    FacesContext.getCurrentInstance().addMessage(null, facesMessage);
                    FacesContext.getCurrentInstance().validationFailed();
                    return;
                }
                
                user = userService.save(user);
                message = "message_successfully_created";
            }
            
        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_optimistic_locking_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_save_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        
        FacesMessage facesMessage = MessageFactory.getMessage(message,
                "User");
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
    }

    public String delete() {
        userService.delete(user);
        FacesMessage facesMessage = MessageFactory.getMessage(
                "message_successfully_deleted", "User");
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
        reset();
        return null;
    }
    
    public void reset() {
        user = null;
        
    }
    
    public SelectItem[] getRolesSelectItems() {
        SelectItem[] items = new SelectItem[UserRole.values().length];

        int i = 0;
        for (UserRole role : UserRole.values()) {
            String label = MessageFactory.getMessageString(
                    "enumeration_label_user_roles_" + role.toString());
            items[i++] = new SelectItem(role, label == null? role.toString() : label);
        }
        return items;
    }
    
    public SelectItem[] getStatusSelectItems() {
        SelectItem[] items = new SelectItem[UserStatus.values().length];

        int i = 0;
        for (UserStatus status : UserStatus.values()) {
            items[i++] = new SelectItem(status, status.toString());
        }
        return items;
    }
    
    public void loadCurrentUser() {
        String username = SecurityWrapper.getUsername();
        if (username != null) {
            this.user = this.userService.findUserByUsername(username);
        } else {
            throw new RuntimeException("Can not get authorized user name");
        }
    }
    
    public boolean isPermitted(String permission) {
        return SecurityWrapper.isPermitted(permission);
    }
}

src/main/webapp/pages/admin/user.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui">
<ui:composition template="/templates/layout.xhtml">
    <ui:define name="content">

        <h:form prependId="false" id="userDataForm"
            onkeypress="if (event.keyCode == 13) {return false; }">

            <p:dataTable id="userTable" value="#{userBean.lazyModel}" var="user"
                resizableColumns="true" paginator="true"
                paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                rowsPerPageTemplate="5,10,25,50" rows="10" draggableColumns="true"
                lazy="true" paginatorPosition="bottom" widgetVar="userTable"
                emptyMessage="#{messages.label_no_records_found}" reflow="true">

                <f:facet name="header">
                    <p:commandButton value="#{messages.create_new_user}"
                        icon="ui-icon-plusthick" title="#{messages.label_create}"
                        action="#{userBean.prepareNewUser()}" update=":createUserDialog"
                        resetValues="true"
                        oncomplete="PF('createUserDialogWidget').show()"
                        style="float:left"
                        rendered="#{security.isPermitted('user:create')}" />
                    <p:commandButton id="toggler" type="button"
                        value="#{messages.table_select_columns}" icon="ui-icon-calculator" />
                    <p:columnToggler datasource="userTable" trigger="toggler" />
                </f:facet>

                <p:column headerText="#{messages.field_label_user_username}"
                          sortBy="#{user.username}" filterBy="#{user.username}">
                    <f:facet name="filter">
                        <p:inputText id="usernameFilter"
                                onkeypress="if (event.keyCode == 13) {PF('userTable').filter(); updateUsernameFilter(); return false; }" >
                            <p:remoteCommand name="updateUsernameFilter" update="userTable:usernameFilter" />
                        </p:inputText>
                    </f:facet>
                    <h:outputText value="#{user.username}" />
                </p:column>

                <p:column headerText="#{messages.field_label_user_email}"
                          sortBy="#{user.email}" filterBy="#{user.email}">
                    <f:facet name="filter">
                        <p:inputText id="emailFilter"
                                onkeypress="if (event.keyCode == 13) {PF('userTable').filter(); updateEmailFilter(); return false; }" >
                            <p:remoteCommand name="updateEmailFilter" update="userTable:emailFilter" />
                        </p:inputText>
                    </f:facet>
                    <h:outputText value="#{user.email}" />
                </p:column>
                
                <p:column headerText="#{messages.field_label_user_status}"
                          sortBy="#{user.status}" filterBy="#{user.status}">
                    <f:facet name="filter">
                        <p:selectOneMenu  id="statusFilter"
                                        style="width:145px;"
                                        onchange="PF('userTable').filter(); return false;">
                            <f:selectItem noSelectionOption="true" itemLabel="" />
                            <f:selectItems value="#{userBean.statusSelectItems}" />
                        </p:selectOneMenu>
                    </f:facet>
                    <h:outputText value="#{user.status.toString()}" />
                </p:column>
                
                <p:column headerText="#{messages.field_label_user_createdAt}"
                          sortBy="#{user.createdAt}">
                    <h:outputText value="#{user.createdAt}"><f:convertDateTime /></h:outputText>
                </p:column>

                <p:column styleClass="action-column"
                    headerText="#{messages.table_actions_column}" width="115"
                    exportable="false">

                    <p:commandButton icon="ui-icon-zoomin" update=":viewUserDialog"
                        oncomplete="PF('viewUserDialogWidget').show()"
                        title="#{messages.label_view}">
                        <f:setPropertyActionListener value="#{user}"
                            target="#{userBean.user}" />
                    </p:commandButton>

                    <p:commandButton icon="ui-icon-pencil" update=":editUserDialog"
                        resetValues="true" oncomplete="PF('editUserDialogWidget').show()"
                        title="#{messages.label_edit}"
                        rendered="#{security.isPermitted('user:update')}">
                        <f:setPropertyActionListener value="#{user}"
                            target="#{userBean.user}" />
                    </p:commandButton>

                    <p:commandButton icon="ui-icon-close"
                        oncomplete="PF('deleteUserDialogWidget').show()"
                        title="#{messages.label_delete}"
                        rendered="#{security.isPermitted('user:delete')}">
                        <f:setPropertyActionListener value="#{user}"
                            target="#{userBean.user}" />
                    </p:commandButton>

                </p:column>

            </p:dataTable>

        </h:form>

        <p:confirmDialog id="deleteUserDialog"
            widgetVar="deleteUserDialogWidget"
            header="#{messages.label_confirm_deletion}" severity="alarm"
            rendered="#{security.isPermitted('user:delete')}">
            <f:facet name="message">
                <h:outputText value="#{messages.label_delete_record}" escape="false" />
            </f:facet>
            <p:outputPanel>
                <h:form>
                    <div style="text-align: center; margin: 10px">
                        <p:commandButton value="#{messages.label_yes}"
                            action="#{userBean.delete}"
                            update=":userDataForm :growlForm:growl"
                            oncomplete="PF('deleteUserDialogWidget').hide()" />
                        <p:commandButton value="#{messages.label_no}"
                            onclick="PF('deleteUserDialogWidget').hide()" type="button" />
                    </div>
                </h:form>
            </p:outputPanel>
        </p:confirmDialog>

        <p:dialog dynamic="true" id="viewUserDialog"
            header="#{messages.label_user_caption}" modal="true"
            widgetVar="viewUserDialogWidget" maximizable="true">
            <p:ajax event="close" listener="#{userBean.reset}" />
            <h:form id="viewUserForm">
                <ui:include src="/pages/admin/userViewInclude.xhtml" />
                <div style="text-align: center; margin: 10px">
                    <p:commandButton value="#{messages.label_close}"
                        icon="ui-icon-close" onclick="PF('viewUserDialogWidget').hide()"
                        type="button" />
                </div>
            </h:form>
        </p:dialog>

        <p:dialog dynamic="true" id="createUserDialog"
            header="#{messages.dialog_header_create_user}" modal="true"
            widgetVar="createUserDialogWidget" maximizable="true"
            rendered="#{security.isPermitted('user:create')}">
            <p:ajax event="close" listener="#{userBean.reset}" />
            <p:outputPanel id="userCreatePanel">
                <h:form id="createUserForm">
                    <ui:include src="/pages/admin/userCreateInclude.xhtml" />
                    <div style="text-align: center; margin: 10px">
                        <p:commandButton value="#{messages.label_save}"
                            icon="ui-icon-disk" action="#{userBean.persist}"
                            update=":userCreatePanel :userDataForm :growlForm:growl"
                            oncomplete="if(!args.validationFailed) PF('createUserDialogWidget').hide()" />
                        <p:commandButton value="#{messages.label_close}"
                            icon="ui-icon-close"
                            onclick="PF('createUserDialogWidget').hide()" type="button" />
                    </div>
                </h:form>
            </p:outputPanel>
        </p:dialog>

        <p:dialog dynamic="true" id="editUserDialog"
            header="#{messages.dialog_header_edit_user}" modal="true"
            widgetVar="editUserDialogWidget" maximizable="true"
            rendered="#{security.isPermitted('user:update')}">
            <p:ajax event="close" listener="#{userBean.reset}" />
            <p:outputPanel id="userEditPanel">
                <h:form id="editUserForm">
                    <ui:include src="/pages/admin/userEditInclude.xhtml" />
                    <div style="text-align: center; margin: 10px">
                        <p:commandButton value="#{messages.label_save}"
                            icon="ui-icon-disk" action="#{userBean.persist}"
                            update=":userEditPanel :userDataForm :growlForm:growl"
                            oncomplete="if(!args.validationFailed) PF('editUserDialogWidget').hide()" />
                        <p:commandButton value="#{messages.label_close}"
                            icon="ui-icon-close" onclick="PF('editUserDialogWidget').hide()"
                            type="button" />
                    </div>
                </h:form>
            </p:outputPanel>
        </p:dialog>

    </ui:define>

</ui:composition>
</html>

src/main/webapp/pages/admin/userCreateInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <h:panelGrid columns="3" styleClass="dialog" columnClasses="col1,col2,col3">

        <h:outputText value="#{messages.field_label_user_username}:" for="usernameEditInput" />
        <p:inputText value="#{userBean.user.username}" id="usernameEditInput" />
        <p:message for="usernameEditInput" display="icon" />
        
        <h:outputText value="#{messages.field_label_user_password}:" for="passwordEditInput" />
        <p:password value="#{userBean.user.password}" id="passwordEditInput" required="true" match="passwordRepeatEditInput"/>
        <p:message for="passwordEditInput" display="icon" />
        
        <h:outputText value="#{messages.field_label_user_password_repeat}:" for="passwordRepeatEditInput" />
        <p:password value="#{userBean.user.password}" id="passwordRepeatEditInput" required="true"/>
        <p:message for="passwordRepeatEditInput" display="icon" />
        
        <h:outputText value="#{messages.field_label_user_email}:" for="emailEditInput" />
        <p:inputText value="#{userBean.user.email}" id="emailEditInput" match="emailRepeatEditInput" required="true"/>
        <p:message for="passwordEditInput" display="icon" />
        
        <h:outputText value="#{messages.field_label_user_email_repeat}:" for="emailRepeatEditInput" />
        <p:inputText value="#{userBean.user.email}" id="emailRepeatEditInput" required="true"/>
        <p:message for="emailRepeatEditInput" display="icon" />
        
        <h:outputText value="#{messages.field_label_user_roles}:" for="userRoles" />
        <h:selectManyCheckbox value="#{userBean.user.roles}" converter="omnifaces.GenericEnumConverter" id="userRolesSelection" collectionType="java.util.ArrayList">
            <f:selectItems value="#{userBean.rolesSelectItems}" />
        </h:selectManyCheckbox>
        <p:message for="userRolesSelection" display="icon" />
        
        <h:outputText value="#{messages.field_label_user_status}:" for="selectUserStatusInput" />
        <p:selectOneMenu value="#{userBean.user.status}" converter="omnifaces.GenericEnumConverter"  id="selectUserStatusInput" required="true">
            <f:selectItems value="#{userBean.statusSelectItems}" />
        </p:selectOneMenu>
        <p:message for="selectUserStatusInput" display="icon" />
        
    </h:panelGrid>

</html>

src/main/webapp/pages/admin/userEditInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <h:panelGrid columns="3" styleClass="dialog" columnClasses="col1,col2,col3">

        <h:outputText value="#{messages.field_label_user_username}:" for="usernameEditInput" />
        <p:inputText value="#{userBean.user.username}" id="usernameEditInput"
            label="#{messages.field_label_user_username}" disabled="#{not request.isUserInRole('Administrator')}" />
        <p:message for="usernameEditInput" display="icon" />
        
        <h:outputText value="#{messages.field_label_user_email}:" for="emailEditInput" />
        <p:inputText value="#{userBean.user.email}" id="emailEditInput" match="emailRepeatEditInput" required="true"
            label="#{messages.field_label_user_email}" disabled="#{not request.isUserInRole('Administrator')}" />
        <p:message for="emailEditInput" display="icon" />
        
        <h:outputText value="#{messages.field_label_user_email_repeat}:" for="emailRepeatEditInput" 
            rendered="#{request.isUserInRole('Administrator')}" />
        <p:inputText value="#{userBean.user.email}" id="emailRepeatEditInput" required="true"
            label="#{messages.field_label_user_email_repeat}"
            rendered="#{request.isUserInRole('Administrator')}"/>
        <p:message for="emailRepeatEditInput" display="icon"
            rendered="#{request.isUserInRole('Administrator')}" />
        
        <h:outputText value="#{messages.field_label_user_roles}:" for="userRoles"/>
        <p:selectManyCheckbox value="#{userBean.user.roles}" converter="omnifaces.GenericEnumConverter" id="userRolesSelection"
                layout="grid" columns="1" collectionType="java.util.ArrayList">
            <f:selectItems value="#{userBean.rolesSelectItems}" />
        </p:selectManyCheckbox>
        <p:message for="userRolesSelection" display="icon" />
        
        <h:outputText value="#{messages.field_label_user_status}:" for="selectUserStatusInput" />
        <p:selectOneMenu value="#{userBean.user.status}" converter="omnifaces.GenericEnumConverter"  id="selectUserStatusInput" required="true">
            <f:selectItems value="#{userBean.statusSelectItems}" />
        </p:selectOneMenu>
        <p:message for="selectUserStatusInput" display="icon" />

    </h:panelGrid>
</html>

src/main/webapp/pages/admin/userViewInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

    <p:outputPanel styleClass="ui-fluid" rendered="#{not security.isPermitted('user:read')}">
        <h:outputText value="#{messages.access_denied}" />
    </p:outputPanel>

    <h:panelGrid columns="2" styleClass="dialog" columnClasses="col1,col2" rendered="#{security.isPermitted('user:read')}">

        <h:outputText value="#{messages.field_label_user_username}:" />
        <h:outputText value="#{userBean.user.username}" />
    
        <h:outputText value="#{messages.field_label_user_email}:" />
        <h:outputText value="#{userBean.user.email}" />
        
        <h:outputText value="#{messages.field_label_user_roles}:" />
        <p:outputPanel>
            <ui:repeat value="#{userBean.user.roles}" var="role">
                <h:outputText value="#{role}" /><br/>
            </ui:repeat>
        </p:outputPanel>
        
        <h:outputText value="#{messages.field_label_user_status}:" />
        <h:outputText value="#{userBean.user.status.toString()}" />
    
        <h:outputText value="#{messages.field_label_user_createdAt}:" />
        <h:outputText value="#{userBean.user.createdAt}" ><f:convertDateTime type="both" /></h:outputText>
        
        <h:outputText value="#{messages.field_label_user_username}:" />
        <h:outputText value="#{userBean.user.username}" />

        <h:outputText value="#{messages.field_label_user_email}:" />
        <h:outputText value="#{userBean.user.email}" />

    </h:panelGrid>
</html>