src/main/java/org/application/web/ProductBean.java
package org.application.web;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;
import javax.persistence.PersistenceException;

import org.application.domain.ItemEntity;
import org.application.domain.ProductEntity;
import org.application.service.ItemService;
import org.application.service.ProductService;
import org.application.service.security.SecurityWrapper;
import org.application.web.generic.GenericLazyDataModel;
import org.application.web.util.MessageFactory;

@Named("productBean")
@ViewScoped
public class ProductBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private static final Logger logger = Logger.getLogger(ProductBean.class.getName());
    
    private GenericLazyDataModel<ProductEntity> lazyModel;
    
    private ProductEntity product;
    
    @Inject
    private ProductService productService;
    
    @Inject
    private ItemService itemService;
    
    private List<ItemEntity> allItemssList;
    
    public void prepareNewProduct() {
        reset();
        this.product = new ProductEntity();
        // set any default values now, if you need
        // Example: this.product.setAnything("test");
    }

    public GenericLazyDataModel<ProductEntity> getLazyModel() {
        if (this.lazyModel == null) {
            this.lazyModel = new GenericLazyDataModel<ProductEntity>(productService);
        }
        return this.lazyModel;
    }
    
    public String persist() {

        String message = "";
        
        try {
            
            if (product.getId() != null) {
                product = productService.update(product);
                message = "message_successfully_updated";
            } else {
                product = productService.save(product);
                message = "message_successfully_created";
            }
        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_optimistic_locking_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_save_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        
        FacesMessage facesMessage = MessageFactory.getMessage(message);
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
        
        FacesContext.getCurrentInstance().getExternalContext().getFlash().setKeepMessages(true);
        
        return null;
    }
    
    public String delete() {
        
        String message = "";
        
        try {
            productService.delete(product);
            message = "message_successfully_deleted";
            reset();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_delete_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        FacesContext.getCurrentInstance().addMessage(null, MessageFactory.getMessage(message));
        
        return null;
    }
    
    public void reset() {
        product = null;

        allItemssList = null;
        
    }

    // Get a List of all items
    public List<ItemEntity> getItemss() {
        if (this.allItemssList == null) {
            this.allItemssList = itemService.findAllItemEntities();
        }
        return this.allItemssList;
    }
    
    // Update items of the current product
    public void updateItems(ItemEntity item) {
        this.product.setItems(item);
        // Maybe we just created and assigned a new item. So reset the allItemsList.
        allItemssList = null;
    }
    
    public ProductEntity getProduct() {
        if (this.product == null) {
            prepareNewProduct();
        }
        return this.product;
    }
    
    public void setProduct(ProductEntity product) {
        this.product = product;
    }
    
    public boolean isPermitted(String permission) {
        return SecurityWrapper.isPermitted(permission);
    }

    public boolean isPermitted(ProductEntity product, String permission) {
        
        return SecurityWrapper.isPermitted(permission);
        
    }
    
}

src/main/webapp/pages/product/product.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui"
      xmlns:dialog="http://java.sun.com/jsf/composite/dialog">
<ui:composition template="/templates/layout.xhtml">
  <ui:define name="content">

    <h:form prependId="false" id="productDataForm" onkeypress="if (event.keyCode == 13) {return false; }">

        <p:dataTable id="productTable" value="#{productBean.lazyModel}" var="product" resizableColumns="true" paginator="true"
                paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                rowsPerPageTemplate="5,10,25,50" rows="10" draggableColumns="true" lazy="true"
                paginatorPosition="bottom" widgetVar="productTable" emptyMessage="#{messages.label_no_records_found}"
                reflow="true">
        
          <f:facet name="header" >

              <p:commandButton value="#{messages.create_new_product}" icon="ui-icon-plusthick"
                      action="/pages/product/productCreate?faces-redirect=true"
                      style="float:left" />
              
              <p:commandButton id="toggler" type="button" value="#{messages.table_select_columns}" icon="ui-icon-calculator" />
              <p:columnToggler datasource="productTable" trigger="toggler" />
          </f:facet>
          
          <p:column  headerText="#{messages.field_label_product_name}" sortBy="#{product.name}" filterBy="#{product.name}">
            <f:facet name="filter">
                <p:inputText id="nameFilter"
                        onkeypress="if (event.keyCode == 13) {PF('productTable').filter(); updateNameFilter(); return false; }" >
                    <p:remoteCommand name="updateNameFilter" update="productTable:nameFilter" />
                </p:inputText>
            </f:facet>
            <h:outputText value="#{product.name}" />
          </p:column>

          <p:column headerText="#{messages.field_label_product_price}" sortBy="#{product.price}" filterBy="#{product.price}">
            <f:facet name="filter">
                <p:inputText id="priceFilter"
                        onkeypress="if (event.keyCode == 13) {PF('productTable').filter(); updatePriceFilter(); return false; }" >
                    <f:convertNumber />
                    <p:remoteCommand name="updatePriceFilter" update="productTable:priceFilter" />
                </p:inputText>
            </f:facet>
            <h:outputText value="#{product.price}"><f:convertNumber /></h:outputText>
          </p:column>

          <p:column headerText="#{messages.field_label_product_stock}" sortBy="#{product.stock}" filterBy="#{product.stock}">
            <f:facet name="filter">
                <p:inputText id="stockFilter"
                        onkeypress="if (event.keyCode == 13) {PF('productTable').filter(); updateStockFilter(); return false; }" >
                    <p:remoteCommand name="updateStockFilter" update="productTable:stockFilter" />
                    <f:convertNumber integerOnly="true" />
                </p:inputText>
            </f:facet>
            <h:outputText value="#{product.stock}" ><f:convertNumber /></h:outputText>
          </p:column>

          <p:column headerText="#{messages.field_label_product_launchDate}" sortBy="#{product.launchDate}" filterBy="#{product.launchDate}">
            <f:facet name="filter">
                <p:inputText id="launchDateFilter"
                        onkeyup="if (event.keyCode == 13) {PF('productTable').filter(); updateLaunchDateFilter(); return false;}" >
                    <p:remoteCommand name="updateLaunchDateFilter" update="productTable:launchDateFilter" />
                    <f:convertDateTime />
                </p:inputText>
            </f:facet>
            <h:outputText value="#{product.launchDate}"><f:convertDateTime /></h:outputText>
          </p:column>

          <p:column headerText="#{messages.field_label_product_discontinued}" sortBy="#{product.discontinued}" filterBy="#{product.discontinued}" exportable="false">
            <f:facet name="filter">
                 <p:selectOneMenu converter="javax.faces.Boolean"
                        onchange="PF('productTable').filter(); return false;" style="width:50%">
                        <f:selectItem itemLabel="&nbsp;" itemValue="" />
                        <f:selectItem itemLabel="#{messages.field_label_product_discontinued_true}" itemValue="true" />
                        <f:selectItem itemLabel="#{messages.field_label_product_discontinued_false}" itemValue="false" />
                </p:selectOneMenu>
            </f:facet>
            <h:panelGroup styleClass="ui-icon ui-icon-check" rendered="#{product.discontinued}"/>
          </p:column>

          <p:column headerText="#{messages.field_label_product_items}" sortBy="#{product.items}" filterBy="#{product.items}">
            <f:facet name="filter">
            <p:selectOneMenu  id="itemsFilter"
                            style="width:145px;"
                            onchange="PF('productTable').filter(); return false;">
                <f:selectItem noSelectionOption="true" itemLabel="" />
                <f:selectItems itemLabel="#{item.id}"
                            value="#{productBean.itemss}" 
                            var="item" 
                            itemValue="#{item}" />
                <o:converter converterId="omnifaces.SelectItemsConverter" list="#{productBean.itemss}" />
            </p:selectOneMenu>
            </f:facet>
            <h:outputText value="#{product.items.id}" />
          </p:column>

          <p:column styleClass="action-column" headerText="#{messages.table_actions_column}" width="115" exportable="false">
            
            <p:commandButton action="#{'/pages/product/productView?faces-redirect=true&amp;id='.concat(product.id)}"
                icon="ui-icon-zoomin"
                title="#{messages.label_view}" />
            
            <p:commandButton action="#{'/pages/product/productEdit?faces-redirect=true&amp;id='.concat(product.id)}"
                icon="ui-icon-pencil"
                resetValues="true"
                title="#{messages.label_edit}" />
                
            <p:commandButton icon="ui-icon-close" 
                oncomplete="PF('deleteProductDialogWidget').show()"
                title="#{messages.label_delete}" >
                <f:setPropertyActionListener value="#{product}"
                    target="#{productBean.product}" />
            </p:commandButton>
    
          </p:column>
          
        </p:dataTable>
        
        <h:panelGrid columns="2">
            <p:panel header="#{messages.export_all_data}">

                <h:commandLink>
                    <h:graphicImage  name="images/excel.png" alt="Excel|" />
                    <p:dataExporter type="xls" target="productTable" fileName="Products"/>
                </h:commandLink>

                <h:commandLink>
                    <h:graphicImage name="images/pdf.png" alt="PDF|" />
                    <p:dataExporter type="pdf" target="productTable" fileName="Products"/>
                </h:commandLink>
                
                <h:commandLink>
                    <h:graphicImage name="images/csv.png" alt="CSV" />
                    <p:dataExporter type="csv" target="productTable" fileName="Products" />
                </h:commandLink>

            </p:panel>
            
            <p:panel header="#{messages.export_page_data}">
                <h:commandLink>
                    <h:graphicImage name="images/excel.png" alt="Excel|" />
                    <p:dataExporter type="xls" target="productTable" fileName="Products" pageOnly="true"/>
                </h:commandLink>

                <h:commandLink>
                    <h:graphicImage name="images/pdf.png" alt="PDF|" />
                    <p:dataExporter type="pdf" target="productTable" fileName="Products" pageOnly="true"/>
                </h:commandLink>
                
                <h:commandLink>
                    <h:graphicImage name="images/csv.png" alt="CSV" />
                    <p:dataExporter type="csv" target="productTable" fileName="Products" pageOnly="true"/>
                </h:commandLink>
                
            </p:panel>
        </h:panelGrid>
        
    </h:form>

    <p:confirmDialog id="deleteProductDialog" widgetVar="deleteProductDialogWidget"
        header="#{messages.label_confirm_deletion}"
        severity="alarm">
        <f:facet name="message"><h:outputText value="#{messages.label_delete_record}" escape="false"/></f:facet>
        <p:outputPanel>
          <h:form>
            <div style="text-align: center; margin:10px">
              <p:commandButton value="#{messages.label_yes}" action="#{productBean.delete}" update=":productDataForm :growlForm:growl" oncomplete="PF('deleteProductDialogWidget').hide()" />
              <p:commandButton value="#{messages.label_no}" onclick="PF('deleteProductDialogWidget').hide()" type="button" />
            </div>
          </h:form>
        </p:outputPanel>
    </p:confirmDialog>
    
  </ui:define>
</ui:composition>
</html>

src/main/webapp/pages/product/productCreate.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <ui:include src="/pages/product/productEdit.xhtml" />

</html>

src/main/webapp/pages/product/productEdit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
<ui:composition template="/templates/layout.xhtml">
  <ui:define name="content">
  
    <f:metadata>
      <f:viewParam name="id" value="#{productBean.product}" converter="#{genericEntityConverter}" />
    </f:metadata>
    
    <p:outputPanel id="productEditPanel">
        <h:form id="editProductForm">
            <ui:include src="/pages/product/productEditInclude.xhtml"/>
            <div style="margin:10px">
                <p:commandButton value="#{messages.label_save}" icon="ui-icon-disk" actionListener="#{productBean.persist}"
                        action="/pages/product/product?faces-redirect=true" update=":productEditPanel :growlForm:growl" />
                <p:commandButton value="#{messages.label_close}" icon="ui-icon-close"
                        action="/pages/product/product?faces-redirect=true" immediate="true" />
            </div>
        </h:form>
    </p:outputPanel>
    
    <p:dialog dynamic="true" id="createItemsFromEditDialog"
        rendered="#{productBean.isPermitted('item:create')}"
        header="#{messages.dialog_product_create_items}" modal="true"
        widgetVar="createItemsFromEditDialogWidget" maximizable="true">
        <p:ajax event="close" listener="#{itemBean.reset}" />
        <p:outputPanel id="createItemsFromEditPanel">
            <h:form id="createItemsFromEditForm">
                <ui:include src="/pages/item/itemEditInclude.xhtml">
                    <ui:param name="hideProductSelectInput" value="true" />
                </ui:include>
                <div style="text-align: center; margin: 10px">
                    <p:commandButton
                        action="#{productBean.updateItems(itemBean.item)}"
                        value="#{messages.label_save}" icon="ui-icon-disk"
                        actionListener="#{itemBean.persist}"
                        update=":editProductForm:itemsSelectInput :createItemsFromEditPanel :growlForm:growl"
                        oncomplete="if(!args.validationFailed) PF('createItemsFromEditDialogWidget').hide()" />
                    <p:commandButton value="#{messages.label_close}"
                        icon="ui-icon-close"
                        onclick="PF('createItemsFromEditDialogWidget').hide()"
                        type="button" />
                </div>
            </h:form>
        </p:outputPanel>
    </p:dialog>
    
  </ui:define>
  
</ui:composition>
</html>

src/main/webapp/pages/product/productEditInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

        <p:outputPanel styleClass="ui-fluid">

            <p:panelGrid columns="3" columnClasses="ui-grid-col-4,ui-grid-col-6,ui-grid-col-2" layout="grid" style="max-width:400px">
            
                <h:outputText value="#{messages.field_label_product_name}:" for="nameEditInput" />
                <p:inputText value="#{productBean.product.name}" id="nameEditInput" 
                    label="#{messages.field_label_product_name}" />
                <p:message for="nameEditInput" display="icon" />

                <h:outputText value="#{messages.field_label_product_price}:" for="priceEditInput" />
                <p:inputText value="#{productBean.product.price}" id="priceEditInput" label="#{messages.field_label_product_price}" >
                    <f:convertNumber />
                </p:inputText>
                <p:message for="priceEditInput" display="icon" />

                <h:outputText value="#{messages.field_label_product_stock}:" for="stockEditInput" />
                <p:inputText value="#{productBean.product.stock}"  id="stockEditInput" 
                    label="#{messages.field_label_product_stock}" />
                <p:message for="stockEditInput" display="icon" />

                <h:outputText value="#{messages.field_label_product_launchDate}:" for="launchDateEditInput" />
                <p:calendar id="launchDateEditInput" navigator="true" value="#{productBean.product.launchDate}" label="#{messages.field_label_product_launchDate}" />
                <p:message for="launchDateEditInput" display="icon" />

                <h:outputText value="#{messages.field_label_product_discontinued}:" for="discontinuedInput" />
                <p:selectBooleanCheckbox value="#{productBean.product.discontinued}" id="discontinuedInput" label="#{messages.field_label_product_discontinued}" />
                <p:message for="discontinuedInput" display="icon" />

                <h:outputText value="#{messages.field_label_product_items}:" for="itemsSelectInput" rendered="#{not hideItemsSelectInput}"/>
                <h:panelGroup rendered="#{not hideItemsSelectInput}">
                    <p:selectOneMenu value="#{productBean.product.items}"
                                    id="itemsSelectInput">
                        <f:selectItem noSelectionOption="true" itemLabel="" />
                        <f:selectItems value="#{productBean.itemss}" 
                                    var="item" 
                                    itemLabel="#{item.id}"
                                    itemValue="#{item}" />
                        <o:converter converterId="omnifaces.SelectItemsConverter" list="#{productBean.itemss}" />
                    </p:selectOneMenu>
                </h:panelGroup>
                <h:panelGroup rendered="#{not hideItemsSelectInput}">
                
                    <p:commandButton icon="ui-icon-plusthick" title="#{messages.label_create}"
                              action="#{itemBean.prepareNewItem()}"
                              update=":createItemsFromEditDialog"
                              resetValues="true"
                              oncomplete="PF('createItemsFromEditDialogWidget').show()"
                              rendered="#{applicationBean.componentExists('createItemsFromEditDialog') and productBean.isPermitted('item:create')}"
                              style="vertical-align:top;" partialSubmit="true" process="@this">
                    </p:commandButton>
                    
                    <p:message for="itemsSelectInput" display="icon" rendered="#{not hideItemsSelectInput}"/>
                </h:panelGroup>
                
            </p:panelGrid>

        </p:outputPanel>
</html>

src/main/webapp/pages/product/productView.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
<ui:composition template="/templates/layout.xhtml">
  <ui:define name="content">
  
    <f:metadata>
      <f:viewParam name="id" value="#{productBean.product}" converter="#{genericEntityConverter}" />
    </f:metadata>
    
    <p:outputPanel id="productViewPanel" >
        <h:form id="viewProductForm">
            <ui:include src="/pages/product/productViewInclude.xhtml"/>
            <div style="margin:10px">
                <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" action="/pages/product/product?faces-redirect=true" immediate="true"/>
            </div>
        </h:form>
    </p:outputPanel>
  
  </ui:define>
  
</ui:composition>
</html>

src/main/webapp/pages/product/productViewInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <h:panelGrid columns="2" styleClass="dialog" columnClasses="col1,col2" >
        
        <h:outputText value="#{messages.field_label_product_name}:" />
        <h:outputText value="#{productBean.product.name}" />

        <h:outputText value="#{messages.field_label_product_price}:" />
        <h:outputText value="#{productBean.product.price}" ><f:convertNumber /></h:outputText>

        <h:outputText value="#{messages.field_label_product_stock}:" />
        <h:outputText value="#{productBean.product.stock}" />

        <h:outputText value="#{messages.field_label_product_launchDate}:" />
        <h:outputText value="#{productBean.product.launchDate}" ><f:convertDateTime /></h:outputText>

        <h:outputText value="#{messages.field_label_product_discontinued}:" for="discontinuedInput" />
        <p:selectBooleanCheckbox disabled="true" value="#{productBean.product.discontinued}" id="discontinuedInput" />

        <h:outputText value="#{messages.field_label_product_items}:" />
        <h:outputText value="#{productBean.product.items.id}" />

    </h:panelGrid>
</html>